# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import multi_pb2 as multi__pb2


class multiplyStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sayHello = channel.unary_unary(
                '/multiply/sayHello',
                request_serializer=multi__pb2.HelloRequest.SerializeToString,
                response_deserializer=multi__pb2.HelloReply.FromString,
                )
        self.askMulti = channel.unary_unary(
                '/multiply/askMulti',
                request_serializer=multi__pb2.NumRequest.SerializeToString,
                response_deserializer=multi__pb2.NumReply.FromString,
                )


class multiplyServicer(object):
    """The greeting service definition.
    """

    def sayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def askMulti(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_multiplyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.sayHello,
                    request_deserializer=multi__pb2.HelloRequest.FromString,
                    response_serializer=multi__pb2.HelloReply.SerializeToString,
            ),
            'askMulti': grpc.unary_unary_rpc_method_handler(
                    servicer.askMulti,
                    request_deserializer=multi__pb2.NumRequest.FromString,
                    response_serializer=multi__pb2.NumReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiply', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class multiply(object):
    """The greeting service definition.
    """

    @staticmethod
    def sayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiply/sayHello',
            multi__pb2.HelloRequest.SerializeToString,
            multi__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def askMulti(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiply/askMulti',
            multi__pb2.NumRequest.SerializeToString,
            multi__pb2.NumReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
