# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmulti.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\nNumRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1a\n\x08NumReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2Z\n\x08multiply\x12(\n\x08sayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12$\n\x08\x61skMulti\x12\x0b.NumRequest\x1a\t.NumReply\"\x00\x42\x12\n\x10org.example.grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020org.example.grpc'
  _HELLOREQUEST._serialized_start=15
  _HELLOREQUEST._serialized_end=43
  _HELLOREPLY._serialized_start=45
  _HELLOREPLY._serialized_end=74
  _NUMREQUEST._serialized_start=76
  _NUMREQUEST._serialized_end=116
  _NUMREPLY._serialized_start=118
  _NUMREPLY._serialized_end=144
  _MULTIPLY._serialized_start=146
  _MULTIPLY._serialized_end=236
# @@protoc_insertion_point(module_scope)
